### ISSUE TITLE
emp_code and category fields not exist

### ISSUE THREAD

**Issue by Sameer1990** [GauravSahu/hr_biometric_machine#4]
Hello,
I wonder what is 'emp_code' and 'category' fields in HR Employee object ?
There are no such like these two fields , so error will appears .

I want to change some code and add some features to your module .
Please let me know further about these fields .

**Comment by GauravSahu** [comment]
emp_code and category are custom field in my module hr.
and in biometric m/c employee registration code is emp_code
Eg:
Employee Name     Employee Code   
Gaurav Sahu          11356

here 11356 is my code 
when i punch in m/c then record is created for 11356

**Comment by Sameer1990** [comment]
Ok , you have to add these fields in this module to let anyone want to add enhancements .

Thanks
