### ISSUE TITLE
Biometric Attendance 

### ISSUE THREAD

**Issue by Jeelkhanpara** [GauravSahu/hr_biometric_machine#6]
I am not able to get data from biometric M/C.
Every Time attendance variable False.

**Comment by GauravSahu** [comment]
shere your m/c detail

**Comment by Jeelkhanpara** [comment]
essl Biometric Attendance System ( E9) Wall Mounted.
SUPC: SDL514063847

Otherwise You Can Show in Below Link
i have purchased from snapdeal 
http://www.snapdeal.com/product/essl-biometric-attendance-system-e9/1083375002

**Comment by GauravSahu** [comment]
hi
your m/c framework is different  
this code is only for zk m/c, i mean zk framework .

**Comment by albosta** [comment]
Hi,
I'm facing this issue:
File "/opt/odoo/odoo/openerp/osv/expression.py", line 812, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'emp_code' in leaf "<osv.ExtendedLeaf: ('emp_code', '=', '1') on hr_employee (ctx: )>"



Your kind help is highly appreciated

**Comment by GauravSahu** [comment]
Hi albosta,

emp_code is my custom field and the type of field is char, so check your field type.

**Comment by albosta** [comment]
Thank you GauravSahu . I managed to get that working by linking to another field. I am having this issue now:
File "/opt/odoo/odoo/addons/hr_biometric_machine/biometric_machine.py", line 41, in download_attendance
    category = hr_employee.browse(cr,uid,employee_id[0]).category
AttributeError: 'hr.employee' object has no attribute 'category'

**Comment by GauravSahu** [comment]
Hi albosta,

category is also my custom field.

**Comment by ahmedwajih** [comment]
did someone solved this err (Invalid field 'emp_code' in leaf "<osv.ExtendedLeaf: ('emp_code', '=', '1') on hr_employee (ctx: )>)
#albosta #GauravSahu

**Comment by ShrikrishnaPatil** [comment]
I am using zk30 machine but zk.connect is not working .please help
