### ISSUE TITLE
Need to classify Sign In and Sign Out!

### ISSUE THREAD

**Issue by ajajmal006** [GauravSahu/hr_biometric_machine#7]
Could you please let me know how i can fetch attendance data based on action Sign In or Sign Out

atten_id = hr_attendance.create(cr,uid,{'name':atten_time,'address_id':address_id.id,'category':category,'day':str(lattendance[2].date()),'employee_id':employee_id[0],'action':'sign_in'})

**Comment by GauravSahu** [comment]
hey
ping me on whatsapp +918090779037
 i will discuss you on it

**Comment by defc0n1** [comment]
I fixed it check it [out](https://github.com/defc0n1/python_zklib)
